export type StateFields =
  | "startDate"
  | "appointmentTime"
  | "firstName"
  | "lastName"
  | "age"
  | "email"
  | "phoneNumber"
  | "tattooStyle"
  | "tattooPlacement"
  | "budget"
  | "referencePhoto"
  | "placementPhoto"
  | "tattooDescription"
  | "requestConfirm";
